version: "3.9"
services:
  chfsd0:
    image: range3/chfs:master
    ports:
      - "50000:50000"
    privileged: true
    networks:
      chfs_net:
        ipv4_address: 172.30.0.2
    command: chfsd -d -p ofi+sockets -h 172.30.0.2:50000
  chfsd1:
    depends_on:
      - chfsd0
    image: range3/chfs:master
    ports:
      - "50001:50000"
    networks:
      chfs_net:
        ipv4_address: 172.30.0.3
    privileged: true
    command: chfsd -d -p ofi+sockets -h 172.30.0.3:50000 ofi+sockets://172.30.0.2:50000

networks:
  chfs_net:
    name: chfs_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/16
